services:
  backend:
    image: ghcr.io/utsc-cscc09-programming-on-the-web/backend-boardshowdown:feat-deploy
    container_name: backend-boardshowdown
    env_file:
      - ./.env.production
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    restart: always
    expose:
      - 3000