services:
  backend:
    image: ghcr.io/utsc-cscc09-programming-on-the-web/backend-boardshowdown:feat-deploy
    container_name: backend-boardshowdown
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=boardshowdown
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=boardshowdown
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: