name: Deploy Stack

on:
  push:  # triggers on every push to any branch

jobs:

  print-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Print VM_DEPLOY secret (first 8 chars)
        run: echo "VM_DEPLOY starts with ${VM_DEPLOY:0:8}"
        env:
          VM_DEPLOY: ${{ secrets.VM_DEPLOY }}

  build-frontend:
    uses: ./.github/workflows/build-frontend.yml

  build-backend:
    uses: ./.github/workflows/build-backend.yml

  deploy:
    needs: [build-frontend, build-backend]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on server
        uses: appleboy/ssh-action@master
        with:
          host: boardshowdown.com
          username: root
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd /path/to/your/project-boardshowdown
            docker compose down -v
            docker system prune -a --volumes -f
            docker compose pull
            docker compose up -d
